%YAML 1.2
---
###############################################################
######               Default configurations                ####
###############################################################

server:
  host: localhost
  port: 8000
